baseURL: "https://nthoang84.github.io" 
title: Hoang Nguyen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
        - name: Research
          url: research/
        - name: Teaching
          url: teaching/

params:
    description: "I am a PhD student in Economics at Brown University, doing research on macroeconomics broadly understood."
    author: Hoang Nguyen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv", "research", "teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hoang Nguyen
          subtitle: "Hello! I am a first-year Economics PhD student at Brown University. I conduct research on macroeconomics broadly understood. Prior to graduate school, I was a predoctoral researcher in the Economics and Computation group at Microsoft Research New England."
          imageUrl: "hoang_brown.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv/
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:hoang.nguyen@brown.edu
        - name: GitHub
          url: https://github.com/nthoang84
        

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hoang Nguyen"
      icon: favicon.png
      iconHeight: 20

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2